import type { Metadata } from 'next';
import Footer from './(layout)/footer';
import Navbar from './(layout)/navbar';
import './globals.css';
import Providers from './providers';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

export default async function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="en">
			<body className="font-sans">
				<Providers>
					<Navbar />
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
