import { AUTH_COOKIE } from '@/utils';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { logout } from './actions';
import './globals.css';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

export default async function RootLayout({ children }: RootLayoutProps) {
	const cookie = cookies().get(AUTH_COOKIE);

	const auth = cookie ? JSON.parse(cookie.value) : null;

	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<nav className="navbar font-sans">
					<div>
						{!auth && (
							<Link href="/register" className="btn">
								Get Started
							</Link>
						)}
						{auth && (
							<form action={logout}>
								<button type="submit" className="btn">
									Log Out
								</button>
							</form>
						)}
					</div>
				</nav>

				{children}
			</body>
		</html>
	);
}
